### ISSUE TITLE
I added support for bzpack -be1 -e to my 86-DOS kernel depacker

### ISSUE THREAD

**Issue by ecm-pushbx** [mbaze/bzpack#4]
Here's [my depacker based on your C++ code](https://hg.pushbx.org/ecm/inicomp/rev/2896c4d7a9f7), it assumes the `-be1 -e` format. Like all my depackers it supports overlapping destination and source buffers. It was very easy to write, I didn't have to fix a single bug. That is, this is my first draft and it appears to work as is.

Here's [the additions to the build scripts](https://hg.pushbx.org/ecm/ldebug/rev/36ec5046a8cd) to assemble my debugger with bzpack used for compression.

**Comment by ecm-pushbx** [comment]
Of course I did find a bug after all. Just one that doesn't affect operation if there are no error conditions: Here's [the fix](https://hg.pushbx.org/ecm/inicomp/rev/a730e4cf3f5d).

**Comment by mbaze** [comment]
Thanks for letting me know, I'll check that out. I was actually taken by surprise that you were so quick to react and to adopt the code because I didn't promote the project in any way yet except that the repository is public :) If you don't mind, I might add the x86 decoder to the project but at the moment I'm still playing with additional formats. Also the ability to build across multiple environments is on my TODO list and I'm well aware of the issue. I'll be closing this because it's more like announcement and not an issue with the code. Nevertheless, your effort is welcome.

**Comment by ecm-pushbx** [comment]
Yeah I found the repo because @tkchia starred it, and I'm following their github or something like that. Feel free to do anything you like with my depacker. (I optimised it some, you can look at the subsequent commits in the inicomp repo.)
